bookshelve/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import (
    path, 
    re_path,
    include
)
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns.extend([
    path('api/', include('product.api.urls')),
])

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import(
    path,
    re_path
)

from product import views

app_name = 'product'
urlpatterns = [
    path('',views.Home_View.as_view(),name='home'),
    path('page_list',views.page_list.as_view(),name='page_list'),
    path('page_add', views.page_add.as_view(),name='page_add'),  
    path('update/<int:id>', views.page_edit,name='page_edit'),
    path('retrieve/<int:id>', views.retrieve),    
    path('delete/<int:id>', views.page_delete),  
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('rate/<int:id>', views.rate_product, name='rate_product'),
    path('recommend/', views.recommend_products, name='recommend_products'),
    #path('product-detail/<str:sku>/', views.ProductDetailView.as_view(), name = "product-detail"),
    #re_path(r'product-detail/(?P<sku>[-\w]+)/(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name = "product-detail"),

]

media/templates/pages/components/banner.html
{% load static %}

<!-- START SECTION BANNER -->
<div class="mt-4 staggered-animation-wrap">
    <div class="custom-container">
        <div class="row">
            <div class="col-lg-7 offset-lg-3">
                <div class="banner_section shop_el_slider">
                    <div id="carouselExampleControls" class="carousel slide carousel-fade light_arrow"
                        data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item {% if  banner.is_default == True %}active{% endif %} background_bg" data-img-src={{ banner.picture.url }}>
                                <div class="banner_slide_content banner_content_inner">
                                    <div class="col-lg-7 col-10">
                                        <div class="banner_content3 overflow-hidden">
                                            <h5 class="mb-3 staggered-animation font-weight-light"
                                                data-animation="{% if LANGUAGE_CODE == 'fa' %}slideInRight{% else %}slideInLeft{% endif %}" data-animation-delay="0.5s">Get up to
                                                50% off Today Only!</h5>
                                            <h2 class="staggered-animation" data-animation="{% if LANGUAGE_CODE == 'fa' %}slideInRight{% else %}slideInLeft{% endif %}"
                                                data-animation-delay="1s">Dual Camera 20MP</h2>
                                            <h4 class="staggered-animation mb-4 product-price"
                                                data-animation="{% if LANGUAGE_CODE == 'fa' %}slideInRight{% else %}slideInLeft{% endif %}" data-animation-delay="1.2s"><span
                                                    class="price">$45.00</span><del>$55.25</del></h4>
                                            <a class="btn btn-fill-out btn-radius staggered-animation text-uppercase"
                                                href={{ banner.url_redirect }} data-animation="{% if LANGUAGE_CODE == 'fa' %}slideInRight{% else %}slideInLeft{% endif %}"
                                                data-animation-delay="1.5s">Shop Now</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <ol class="carousel-indicators indicators_style3">
                                <li data-target="#carouselExampleControls" data-slide-to={{ forloop.counter0 }} class="{% if  banner.is_default == True %}active{% endif %}"></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END SECTION BANNER -->

media/templates/pages/components/bread_crumb.html
<!-- START SECTION BREADCRUMB -->
<div class="breadcrumb_section bg_gray page-title-mini">
    <div class="container">
        <!-- STRART CONTAINER -->
        
        </div>
    </div><!-- END CONTAINER-->
</div>
<!-- END SECTION BREADCRUMB -->

media/templates/pages/components/home_footer.html
{% load static %}
<!-- START FOOTER -->
<footer class="bg_gray">
    <div class="footer_top small_pt pb_20">
        <div class="custom-container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="widget">
                        <div class="footer_logo">
                            <a href="#"><img src="{% static 'assets/images/logo_dark.png' %}" alt="logo" /></a>
                        </div>
                        <p class="mb-3">If you are going to use of Lorem Ipsum need to be sure there isn't anything
                            hidden of text</p>
                        <ul class="contact_info">
                            <li>
                                <i class="ti-location-pin"></i>
                                <p>123 Street, Old Trafford, NewYork, USA</p>
                            </li>
                            <li>
                                <i class="ti-email"></i>
                                <a href="mailto:info@sitename.com">info@sitename.com</a>
                            </li>
                            <li>
                                <i class="ti-mobile"></i>
                                <p>+ 457 789 789 65</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <div class="widget">
                        <h6 class="widget_title">Useful Links</h6>
                        <ul class="widget_links">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#">Location</a></li>
                            <li><a href="#">Affiliates</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <div class="widget">
                        <h6 class="widget_title">My Account</h6>
                        <ul class="widget_links">
                            <li><a href="#">My Account</a></li>
                            <li><a href="#">Discount</a></li>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Orders History</a></li>
                            <li><a href="#">Order Tracking</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="widget">
                        <h6 class="widget_title">Instagram</h6>
                        <ul class="widget_instafeed instafeed_col4">
                            <li><a href="#"><img src="{% static 'assets/images/insta_img1.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img2.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img3.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img4.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img5.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img6.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img7.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                            <li><a href="#"><img src="{% static 'assets/images/insta_img8.jpg' %}" alt="insta_img"><span
                                        class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="middle_footer">
        <div class="custom-container">
            <div class="row">
                <div class="col-12">
                    <div class="shopping_info">
                        <div class="row justify-content-center">
                            <div class="col-md-4">
                                <div class="icon_box icon_box_style2">
                                    <div class="icon">
                                        <i class="flaticon-shipped"></i>
                                    </div>
                                    <div class="icon_box_content">
                                        <h5>Free Delivery</h5>
                                        <p>Phasellus blandit massa enim elit of passage varius nunc.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="icon_box icon_box_style2">
                                    <div class="icon">
                                        <i class="flaticon-money-back"></i>
                                    </div>
                                    <div class="icon_box_content">
                                        <h5>30 Day Returns Guarantee</h5>
                                        <p>Phasellus blandit massa enim elit of passage varius nunc.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="icon_box icon_box_style2">
                                    <div class="icon">
                                        <i class="flaticon-support"></i>
                                    </div>
                                    <div class="icon_box_content">
                                        <h5>27/4 Online Support</h5>
                                        <p>Phasellus blandit massa enim elit of passage varius nunc.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom_footer border-top-tran">
        <div class="custom-container">
            <div class="row">
                <div class="col-lg-4">
                    <p class="mb-lg-0 text-center">© 2020 All Rights Reserved by Bestwebcreator</p>
                </div>
                <div class="col-lg-4 order-lg-first">
                    <div class="widget mb-lg-0">
                        <ul class="social_icons text-center text-lg-left">
                            <li><a href="#" class="sc_facebook"><i class="ion-social-facebook"></i></a></li>
                            <li><a href="#" class="sc_twitter"><i class="ion-social-twitter"></i></a></li>
                            <li><a href="#" class="sc_google"><i class="ion-social-googleplus"></i></a></li>
                            <li><a href="#" class="sc_youtube"><i class="ion-social-youtube-outline"></i></a></li>
                            <li><a href="#" class="sc_instagram"><i class="ion-social-instagram-outline"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4">
                    <ul class="footer_payment text-center text-lg-right">
                        <li><a href="#"><img src="{% static 'assets/images/visa.png' %}" alt="visa"></a></li>
                        <li><a href="#"><img src="{% static 'assets/images/discover.png' %}" alt="discover"></a></li>
                        <li><a href="#"><img src="{% static 'assets/images/master_card.png' %}" alt="master_card"></a>
                        </li>
                        <li><a href="#"><img src="{% static 'assets/images/paypal.png' %}" alt="paypal"></a></li>
                        <li><a href="#"><img src="{% static 'assets/images/amarican_express.png' %}" alt="amarican_express"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- END FOOTER -->

media/templates/pages/components/home_header.html
{% load static %}


<!-- START HEADER -->
<header class="header_wrap">
    <div class="top-header light_skin bg_dark d-none d-md-block">
        <div class="custom-container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-8">
                    <div class="header_topbar_info">
                        <span>Ninja E-Commerce Website: Slogan!</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="middle-header dark_skin">
        <div class="custom-container">
            <div class="nav_block">
           
                <div class="product_search_form rounded_input">
                    <form>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="custom_select">
                                    <select class="first_null">
                                        <option value="">All Category</option>
                                        <option value="Dresses">Dresses</option>
                                        <option value="Shirt-Tops">Shirt & Tops</option>
                                        <option value="T-Shirt">T-Shirt</option>
                                        <option value="Pents">Pents</option>
                                        <option value="Jeans">Jeans</option>
                                    </select>
                                </div>
                            </div>
                            <input class="form-control" placeholder="Search Product..." required="" type="text">
                            <button type="submit" class="search_btn2"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
                <ul class="navbar-nav attr-nav align-items-center">
                    <li>
                            <a href="{% url 'product:login' %}" class="nav-link">
                                <i class="linearicons-user-lock"></i>
                            </a>
                            <a href="{% url 'product:logout' %}">Log out</a>
                    </li>
                   
                    
                    <li class="dropdown cart_dropdown"><a class="nav-link cart_trigger" href="#"
                            data-toggle="dropdown"><i class="linearicons-bag2"></i><span
                                class="cart_count">2</span><span class="amount"><span
                                    class="currency_symbol">$</span>159.00</span></a>
                        <div class="cart_box cart_right dropdown-menu dropdown-menu-right">
                            <ul class="cart_list">
                                <li>
                                    <a href="#" class="item_remove"><i class="ion-close"></i></a>
                                    <a href="#"><img src="{% static 'assets/images/cart_thamb1.jpg' %}"
                                            alt="cart_thumb1">Variable
                                        product 001</a>
                                    <span class="cart_quantity"> 1 x <span class="cart_amount"> <span
                                                class="price_symbole">$</span></span>78.00</span>
                                </li>
                                <li>
                                    <a href="#" class="item_remove"><i class="ion-close"></i></a>
                                    <a href="#"><img src="{% static 'assets/images/cart_thamb2.jpg' %}"
                                            alt="cart_thumb2">Ornare
                                        sed consequat</a>
                                    <span class="cart_quantity"> 1 x <span class="cart_amount"> <span
                                                class="price_symbole">$</span></span>81.00</span>
                                </li>
                            </ul>
                            <div class="cart_footer">
                                <p class="cart_total"><strong>Subtotal:</strong> <span class="cart_price"> <span
                                            class="price_symbole">$</span></span>159.00</p>
                                            
                                <p class="cart_buttons"><a href="#" class="btn btn-fill-line view-cart">View
                                        Cart</a><a href="#" class="btn btn-fill-out checkout">Checkout</a></p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="bottom_header dark_skin main_menu_uppercase border-top border-bottom">
        <div class="custom-container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 col-3">
                    <div class="categories_wrap">
                        <button type="button" data-toggle="collapse" data-target="#navCatContent" aria-expanded="false"
                            class="categories_btn">
                            <i class="linearicons-menu"></i><span>All Categories </span>
                        </button>
                        <div id="navCatContent" class="nav_cat navbar collapse">
                            <ul>
                                {% if node.level == 0 %}
                                <li class="dropdown dropdown-mega-menu">
                                    <a class="dropdown-item nav-link dropdown-toggler" href="#"
                                        data-toggle="dropdown"><i class="flaticon-plugins"></i>
                                        <span>{{ node.title }}</span></a>
                                    <div class="dropdown-menu">
                                        <ul class="mega-menu d-lg-flex">
                                            {% endif %}
                                            {% if node.level == 1 %}
                                            <li class="mega-menu-col col-lg-4">
                                                <ul>
                                                    <li class="dropdown-header">{{ node.title }}</li>
                                                    {% endif %}
                                                    {% if node.level == 2 %}
                                                    <li><a class="dropdown-item nav-link nav_item"
                                                            href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                                                    {% endif %}
                                                    {% if not node.is_leaf_node and node.level == 0 %}
                                                        {{ children }}
                                                    </ul>
                                                </div>
                                        </li>
                                                    {% endif %}
                                                    {% if not node.is_leaf_node and node.level == 1 %}
                                                        {{ children }}
                                                    </ul>
                                                </li>
                                                {% endif %}

                            </ul>
                            {% if categories.count > 7 %}
                            <div class="more_categories">More Categories</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-8 col-sm-6 col-9">
                    <nav class="navbar navbar-expand-lg">
                        <button class="navbar-toggler side_navbar_toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSidetoggle" aria-expanded="false">
                            <span class="ion-android-menu"></span>
                        </button>
                        <div class="pr_search_icon">
                            <a href="javascript:void(0);" class="nav-link pr_search_trigger"><i
                                    class="linearicons-magnifier"></i></a>
                        </div>
                        <div class="collapse navbar-collapse mobile_side_menu" id="navbarSidetoggle">
                            <ul class="navbar-nav">
                                {% include 'pages/components/nav-links.html' %}
                            </ul>
                        </div>
                        <div class="contact_phone contact_support">
                            <i class="linearicons-phone-wave"></i>
                            <span>123-456-7689</span>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- END HEADER -->

media/templates/pages/components/nav-links.html
<li>
    <a 
    class="nav-link nav_item {% if view.page_name == 'page_list' %}active{% endif %}"
    href="{% url 'product:page_list' %}">
    
    Products
    </a>
</li>

media/templates/pages/components/pages_header.html
{% load static %}

<!-- START HEADER -->
<header class="header_wrap fixed-top header_with_topbar">
    <div class="top-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="page-title">
                        <h1>Product List</h1>
                    </div>
                </div>
                <div class="col-md-6">
                    <ol class="breadcrumb justify-content-md-end">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Pages</a></li>
                        <li class="breadcrumb-item active">{{ view.page_name }}</li>
                        <li class="text-center text-md-right">
                            <ul class="header_list">
                                <li>
                                    <a class="top-nav {% if view.page_name == 'auth-login' %}active{% endif %}" href="{% url 'product:login' %}">
                                        <i class="ti-user"></i><span>&nbsp;Login</span>
                                    </a>
                                    <a href="{% url 'product:logout' %}">&nbsp;Logout</a>
                                    <a href="http://127.0.0.1:8000/admin/product/product/add/" >&nbsp;Create</a> <!--{% url 'product:page_add' %} -->
                                    <a href="/signup/" class="btn btn-primary">&nbsp;signup</a>
                                    <a href="{% url 'product:recommend_products' %}">&nbsp;Recommend</a>
                                </li>
                            </ul>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <br/><br/>
    
    <div class="bottom_header dark_skin main_menu_uppercase">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-expanded="false">
                    <span class="ion-android-menu"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <div class="product_header_right" align="right">
                            <form method="get">
                                <select class="form-control-sm" name='paginate_by' onchange="this.form.submit()">
                                    <option selected="selected" value="">Show</option>
                                    {% for choice in pagination_choices %}
                                    <option {% if choice == request.GET.paginate_by %} selected="selected" {% endif %} value="{{ choice }}">{{ choice }}</option>
                                    {% endfor %}
                                </select>
                                <input type="hidden">
                            </form>
                            <ul class="navbar-nav" style="align-items-right">
                                <li>
                                    <div class="search_wrap">
                                        <span class="close-search"><i class="ion-ios-close-empty"></i></span>
                                        <form method="get" action="{% if view.page_name == 'page_list' and request.resolver_match.kwargs.id %}{% url 'product:page_list' request.resolver_match.kwargs.id %}{% else %}{% url 'product:page_list' %}{% endif %}" id="form1">
                                            <a href="javascript:void(0);" class="nav-link search_trigger"><i class="linearicons-magnifier"></i></a>
                                            <input type="text" placeholder="Search" {% if request.GET.search %} value="{{ request.GET.search }}" {% endif %} class="form-control" id="search_input" name="search">
                                            <button type="submit" class="search_icon"><i class="ion-ios-search-strong"></i></button>
                                        </form>
                                    </div>
                                    <div class="search_overlay"></div>
                                </li>
                                <li class="dropdown cart_dropdown"><a class="nav-link cart_trigger" href="#"
                                        data-toggle="dropdown"><i class="linearicons-cart"></i><span class="cart_count">2</span></a>
                                    <div class="cart_box dropdown-menu dropdown-menu-right">
                                        <ul class="cart_list">
                                            <li>
                                                <a href="#" class="item_remove"><i class="ion-close"></i></a>
                                                <a href="#"><img src="{% static 'assets/images/cart_thamb1.jpg' %}" alt="cart_thumb1">
                                                    Variable product 001</a>
                                                <span class="cart_quantity">1 x 
                                                    <span class="cart_amount"> 
                                                        <span class="price_symbole">$</span>
                                                    </span>78.00
                                                </span>
                                            </li>
                                        </ul>
                                        <div class="cart_footer" style="Inline">
                                            <p class="cart_total" >
                                                <strong>Subtotal:</strong> 
                                                <span class="cart_price"> <span class="price_symbole">$</span></span>159.00
                                                <a href="#" class="btn btn-fill-line view-cart">View Cart</a>
                                            </p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>

                    </ul>
                </div>
            </nav>

        </div>
    </div>
    
</header>
<!-- END HEADER -->

media/templates/pages/components/pagination.html
<div class="row">
    <div class="col-12">
        {% if is_paginated %}
        <ul class="pagination mt-3 justify-content-center pagination_style1">

            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <i class="linearicons-arrow-left"></i>
                </a>
            </li>
            {% endif %}

            {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
            <li class="page-item active">
                <a class="page-link">{{ page }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <i class="linearicons-arrow-right"></i>
                </a>
            </li>
            {% endif %}

        </ul>
        {% endif %}
    </div>
</div>