bookshelve/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import (
    path, 
    re_path,
    include
)
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns.extend([
    path('api/', include('product.api.urls')),
])

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import(
    path,
    re_path
)

from product import views

app_name = 'product'
urlpatterns = [
    path('',views.Home_View.as_view(),name='home'),
    path('page_list',views.page_list.as_view(),name='page_list'),
    path('page_add', views.page_add.as_view(),name='page_add'),  
    path('update/<int:id>', views.page_edit,name='page_edit'),
    path('retrieve/<int:id>', views.retrieve),    
    path('delete/<int:id>', views.page_delete),  
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('rate/<int:id>', views.rate_product, name='rate_product'),
    path('recommend/', views.recommend_products, name='recommend_products'),
    #path('product-detail/<str:sku>/', views.ProductDetailView.as_view(), name = "product-detail"),
    #re_path(r'product-detail/(?P<sku>[-\w]+)/(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name = "product-detail"),

]

media/templates/pages/user/login.html
{% comment %} {% extends 'product/page_list.html' %} {% endcomment %}

{% block content %}
  <form action="{% url 'product:login' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Log in</button>
  </form>
  <p>Don't have an account? <a href="{% url 'product:signup' %}">Sign up!</a></p>
{% endblock content %}

media/templates/pages/user/page-detail.html
<!DOCTYPE html>
{%block content%}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>my_page</title>
    <a style="background-color:red;"href="http://127.0.0.1:8000/admin/product/product1/add/">add product</a> -->
</head>
<body >
    {% if user.is_authenticated %}
      <form method="POST"enctype="multipart/form-data"action="{% url 'product:page_list' %}"><br>
        {% csrf_token %}
      <!-- <p>{{x.UserName}}</p> -->
            {%for z in cat.all%}

      <div class="divconfig1">
        <h1>{{cat.title}}:'fruits'</h1><br>
      {%endfor%}
        {%for x in products.all%}
        <ul id="border">
        <button id="border" >
        <div class="divconfig2"><img style="height:80px;width:80px"src="{{x.pic.url }}"alt="icon",default=""><br>
          <h2>{{x.title}}</h2><br>
          <p>size:{{x.size}}</p><br>
          <p>caption:{{x.body|safe}}</p><br>
          <p>price:{{x.price}}</p><br>
          <p>cdate:{{x.cdate}}</p><br>
          <p>published:{{x.published}}</p>
        </div>
        </button><br><br>
      </ul>
      {%endfor%}
      {% csrf_token %}
    <select class="form-control mb4" name="category">
      {%for c in cat.all%}
          <option value="{{c.id}}">{{c.name}}</option>
      {%endfor%}
    <select/>
      </div>
    </form><br>
    {%endif%}
    <!-- <form class="form2"method="POST"enctype="multipart/form-data"action="{% url 'product:page_list' %}"><br>
    {% csrf_token %}
    <div class="divconfig3">
      <h3>vegtables:</h3>
      {%for y in products2.all%}
      <ul>
      <button id="border">
      <div class="divconfig2"><img style="height:80px;width:80px"src="{{y.pic.url }}"alt="icon"><br>
        <h2>{{y.title}}</h2><br>
        <p>size:{{y.size}}</p><br>
        <p>caption:{{y.body|safe}}</p><br>
        <p>price:{{y.price}}</p><br>
      </div>
      </button><br><br>
    </ul>
    {%endfor%}
    </div>
    </form> -->
</body>

<style>
.back{
  background-color:#1111111;
}
.divconfig1{
    background-color:#cc0000;
    width: 100p%;
    height: 100p%;
    position: absolute ;
    right: 0;
    left: 0;
    text-align: center;
}
.divconfig2{
    padding-right: 30px;
    padding-left: 50px;


}
#border{
    display: inline-block;
}
.form2{
  padding-top: 370px;
}
.divconfig3{
  background-color:green;
  width: 100p%;
  height: 100p%;
  position: absolute ;
  right: 0;
  left: 0;
  text-align: center;
}

</style>

<body>
</body>

</html>
{%endblock%}

media/templates/pages/user/page_add.html
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>page_add</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
  </head>  

<body style="text-align: center;">  
<form name="PostForm" method="POST" class="post-form" action="{% url 'product:page_list' %}" enctype="multipart/form-data">  
  {% csrf_token %}  
  <div class="container">  
    <br>  
    <div class="form-group row">  
      <label class="col-sm-1 col-form-label"></label>  
      <div class="col-sm-4">  
        <h3>Enter Details</h3>  
      </div>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">title:</label>  
    <input type="text" name="title" /> 
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">summary:</label>  
    <input type="text" name="summary" />
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">stock:</label>  
    <input type="number" name="stock" /> 
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">category:</label>  
    <input type="text" name="category" value="bmv"/>
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">picture:</label>  
    <input type="file" accept=".jpg"name="picture" />
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">created:</label>  
    <input type="time" name="time" />
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">modified:</label>  
    <input type="time" name="time" />
  </div>
  <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" value="add" class="btn btn-primary"><a href="{% url 'product:page_list' %}">Submit</a></button>  
    </div>  
  </div>  
    </div>  
</form>  
<div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-primary"><a href="{% url 'product:page_list' %}">انصراف</a></button>  
  </div>  
</div>  
</body>  
</html>  

media/templates/pages/user/page_list.html
{% load static %}
{% block header %}
    {% include 'pages/partials/meta_tags.html' %}
    {% include 'pages/partials/scripts.html' %}
    <!-- SITE TITLE -->
    <title>Products Template</title>
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <!-- Google Font -->

        {% include 'pages/partials/styles.html' %}
        {% block extra_styles %}
        {% endblock extra_styles %}



        {% if view.page_name == 'home' %}
            {% include 'pages/components/home_header.html' %}
        {% else %}
            {% include 'pages/components/pages_header.html' %}
            {% include 'pages/components/bread_crumb.html' %}
        {% endif %}
{% endblock header %}
<br/><br/>
<br/>

{% block body %}
<body style="background-color:lavender">
    {% if user.is_authenticated %}
        <div class="divconfig1">
            {% for product in products %}  
            <ul id="border">
            <button id="border" style="background-color:TEAL" >
            <div class="divconfig2">
                {% if product.picture %}
                <img style="height:80px;width:80px"src="{{product.picture.url }}" alt="icon"><br>
                {% else %}
                <img style="height:80px;width:80px"src="{% static 'assets/images/product4.png' %}" alt="icon"><br>
                {%endif%}
                <h2>{{product.title}}</h2><br>
                <p>summary:{{product.summary}}</p><br>
                <p>is_active:{{product.is_active|safe}}</p><br>
                <p>is_special:{{product.is_special}}</p><br>
                <p>stock:{{product.stock}}</p><br>
                <p>rating:{{product.rating.rating}}</p>
                <p>category:{{product.category}}</p>
                <p>genre:{{product.genre.title}}</p>
                <a href="/update/{{ product.id }}"><a class="glyphicon glyphicon-pencil" >Update</a></a>  
                <a href="/delete/{{ product.id }}">Delete</a>  
                <a href="/retrieve/{{ product.id }}">Retrieve</a> <br>
                <a href="{% url 'product:rate_product' product.id %}">Rate</a>
            </div>
            </button>
            </ul>
            {%endfor%}
        </div>
        <br>
    {%endif%}

    </br>
    <div class="row">
        <div class="col-12">
            {% include 'pages/components/pagination.html' %}
        </div>
    </div>
</body>

    <style>
       
        .divconfig1{
            background-color:white;
            position: absolute ;
            right: 0;
            left: 0;
            text-align: center;
        }
        .divconfig2{
            padding-right: 30px;
            padding-left: 50px;
        
        }
        #border{
            display: inline-block;
        }
        
        </style>
        
        
{% endblock body %} 
{% block content %}
<form method="get" action="{% url 'product:page_list' %}">
    <input type="text" name="search" placeholder="Search for products..." value="{{ request.GET.search }}">
    <button type="submit">Search</button>
</form>

{% for product in products %}
    <div>
        <h2>{{ product.title }}</h2>
        <p>{{ product.summary }}</p>
    </div>
{% endfor %}
{% endblock %}

media/templates/pages/user/rate.html
<br/>
{% block content %}
<h1>Rate {{ product.title }}</h1>
<form method="post" >
    {% csrf_token %}
    <label for="rating">Rating:</label>
    <select name="rating" id="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select>
    <button type="submit">Submit</button>
</form>
{% endblock %}

media/templates/pages/user/recommend.html
{% block content %}
<h1>Recommended Books</h1>
<ul>
    {% for recommended in recommended %}
        <li>{{ recommended.title }} by {{ recommended.user }}</li>
    {% endfor %}
</ul>
{% endblock %}

media/templates/pages/user/register.html
{% load static %}
{% block header %}
    {% include 'pages/partials/meta_tags.html' %}
    {% include 'pages/partials/scripts.html' %}
    <!-- SITE TITLE -->
    <title>Products Template</title>
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}"/>  
    <!-- Google Font -->

        {% include 'pages/partials/styles.html' %}
        {% block extra_styles %}
        {% endblock extra_styles %}
      
        
        
        {% if view.page_name == 'home' %}
            {% include 'pages/components/home_header.html' %}
        {% else %}
            {% include 'pages/components/bread_crumb.html' %}
        {% endif %}
{% endblock header %}
<br/><br/>
<br/>

{% block body %}
<!-- START SIGNUP SECTION -->
<div class="login_register_wrap section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-6 col-md-10">
                <div class="login_wrap">
                    <div class="padding_eight_all bg-white">
                        <div class="heading_s1">
                            <h3>Create an Account</h3>
                        </div>
                        <form action="{% url 'product:signup' %}" method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                            {% endfor %}
                            <div class="login_footer form-group">
                                <div class="chek-form">
                                    <div class="custome-checkbox">
                                        <input class="form-check-input" type="checkbox" name="checkbox"
                                            id="exampleCheckbox2" value="">
                                        <label class="form-check-label" for="exampleCheckbox2"><span>I agree to terms
                                                &amp; Policy.</span></label>
                                    </div>
                                </div>
                            </div>
                            <button type="submit">Sign up</button>
                          </form>
                        <div class="different_login">
                            <span> or</span>
                        </div>
                        <ul class="btn-login list_none text-center">
                            <li><a href="#" class="btn btn-facebook"><i class="ion-social-facebook"></i>Facebook</a>
                            </li>
                            <li><a href="#" class="btn btn-google"><i class="ion-social-googleplus"></i>Google</a></li>
                        </ul>
                        <div class="form-note text-center">Already have an account? <a
                                href="{% url 'product:login' %}">Log in</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END SIGNUP SECTION -->


{% endblock body %}

media/templates/pages/user/retrieve.html
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Retrieve</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body style="text-align: center;">  
    <form method="POST" class="post-form" action="/retrieve/{{Post.id}}">  
    {% csrf_token %}  
<div class="main">

{% for product in products %}      
    <div class="form-group row">  
        <label class="col-sm-2 col-form-label">title:</label>  
        <div class="col-sm-4">  
          {{ product.title }}  
        </div>  
      </div> 
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">id:</label>  
        <div class="col-sm-4">  
          {{ product.id }}  
        </div>  
      </div>  
    <hr/>
{% endfor %}
 
</div>
</body> 
</hrml> 

media/templates/pages/user/signup.html
{% comment %} {% extends './signup.html' %} {% endcomment %}

{% block content %}
  <form action="{% url 'product:signup' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Sign up</button>
    <p>Already have an account? <a href="{% url 'product:login' %}">Log in!</a></p>
  </form>
{% endblock content %}

media/templates/pages/user/update.html
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Update</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
  </head>  
<body>  
<form nem="update" method="POST" class="post-form" action="/update/{{products.id}}">  
        {% csrf_token %}  
    <div class="container"><br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>edit Details</h3>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">title:</label>  
    <div class="col-sm-4">  
      {{ products.title }}  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">summary:</label>  
    <div class="col-sm-4">  
      {{ products.summary }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">is_active:</label>  
    <div class="col-sm-4">  
      {{ products.is_active }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">is_special:</label>  
    <div class="col-sm-4">  
      {{ products.is_special }}  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">stock:</label>  
    <div class="col-sm-4">  
      {{ products.stock }}  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">rating:</label>  
    <div class="col-sm-4">  
      {{ products.rating }}  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">category:</label>  
    <div class="col-sm-4">  
      {{ products.category }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">picture:</label>  
    <div class="col-sm-4">  
      {{ products.picture }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary"><a href="{% url 'product:page_list' %}">Update</a></button>  
    </div>  
  </div>  
    </div>  
</form>  
<div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-primary"><a href="{% url 'product:page_list' %}">انصراف</a></button>  
  </div>  
</div>  
</body>  
</html>    
</form>  
</body>  
</html> 